module.exports = [
  {
    alertId: 1,
    bookingId: 41,
    offenderNo: '111111',
    alertType: 'string',
    alertTypeDescription: 'string',
    alertCode: 'string',
    alertCodeDescription: 'string',
    comment: 'string',
    dateCreated: '2019-01-30',
    dateExpires: '2019-10-31',
    expired: false,
    active: true,
    addedByFirstName: 'Bill',
    addedByLastName: 'Badger',
    expiredByFirstName: 'Ned',
    expiredByLastName: 'Kelly',
  },
  {
    alertId: 2,
    bookingId: 42,
    offenderNo: '222222',
    alertType: 'string',
    alertTypeDescription: 'string',
    alertCode: 'string',
    alertCodeDescription: 'string',
    comment: 'string',
    dateCreated: '2019-02-05',
    dateExpires: '2019-11-21',
    expired: false,
    active: true,
    addedByFirstName: 'Bill',
    addedByLastName: 'Badger',
    expiredByFirstName: 'Ned',
    expiredByLastName: 'Kelly',
  },
]
